### ISSUE TITLE
Deprecation warnings when using sailor

### ISSUE THREAD

**Issue by zubairov** [elasticio/sailor-nodejs#43] opened 2017-01-26 14:37 UTC
I can see this during ``npm install``:

```
npm WARN deprecated node-uuid@1.3.3: use uuid module instead
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

**Comment by drobiazko** [comment] 2017-02-23 10:30
This is caused by https://www.npmjs.com/package/elasticio-node. The new version 0.0.8 has all dependencies updated. Closing.

**Closed by drobiazko** 2017-02-23 10:30 UTC
